//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlInventario
    {
        public int IdControlInventario { get; set; }
        public Nullable<int> IdInventario { get; set; }
        public Nullable<int> IdPersonal { get; set; }
        public int EstadoActivo { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public System.DateTime FechaIngresa { get; set; }
        public string Anomalias { get; set; }
    
        public virtual Inventario Inventario { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
