//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlVehiculo
    {
        public int IdControlVehiculo { get; set; }
        public Nullable<int> IdFlotilla { get; set; }
        public Nullable<int> IdPersonal { get; set; }
        public int EstadoVehiculo { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public int KilometrajeSalida { get; set; }
        public System.DateTime FechaIngresa { get; set; }
        public int KilometrajeIngresa { get; set; }
        public string Anomalias { get; set; }
    
        public virtual Flotilla Flotilla { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
