//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCA.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Flotilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flotilla()
        {
            this.ControlVehiculo = new HashSet<ControlVehiculo>();
            this.MantenimientoVehiculo = new HashSet<MantenimientoVehiculo>();
        }

        public int IdFlotilla { get; set; }
        public int Placa { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int Traccion { get; set; }
        public int Ano { get; set; }
        public int Combustible { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public int CostoVehiculo { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> MotivoDeshabilitar { get; set; }
        public string ValorNuevo()
        {
            return "Ano:" + Ano + " |Combustible:" + Combustible + " |CostoVehiculo:" + CostoVehiculo+ "|FechaCompra:"+ FechaCompra.ToString()+ " |IdDepartamento:"+ IdDepartamento+ " |IdFlotilla:"+ IdFlotilla+ " |Marca:"+ Marca+ " |Modelo:"+ Modelo+ " |Placa:"+Placa+ " |Traccion:"+ Traccion;
        }
        public string ValorAntiguo(Flotilla Entidad) {
            return "Ano:" + Entidad.Ano + " |Combustible:" + Entidad.Combustible + " |CostoVehiculo:" + Entidad.CostoVehiculo + "|FechaCompra:" + Entidad.FechaCompra.ToString() + " |IdDepartamento:" + Entidad.IdDepartamento + " |IdFlotilla:" + Entidad.IdFlotilla + " |Marca:" + Entidad.Marca + " |Modelo:" + Entidad.Modelo + " |Placa:" + Entidad.Placa + " |Traccion:" + Entidad.Traccion;
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlVehiculo> ControlVehiculo { get; set; }
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoVehiculo> MantenimientoVehiculo { get; set; }
    }
}
