//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventario()
        {
            this.ControlInventario = new HashSet<ControlInventario>();
            this.MantenimientoInventario = new HashSet<MantenimientoInventario>();
        }
        [Display(Name = "Id del inventario")]
        public int IdInventario { get; set; }
        [Display(Name = "Codigo de la empresa")]
        [Required(ErrorMessage = "El codigo de la empresa es requerido")]
        public string CodigoEmpresa { get; set; }
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "El Nombre es requerido")]
        public string Nombre { get; set; }
        [Display(Name = "Modelo")]
        [Required(ErrorMessage = "El Modelo es requerido")]
        public string Modelo { get; set; }
        [Display(Name = "Serie")]
        [Required(ErrorMessage = "La serie es requerida")]
        public string Serie { get; set; }
        [Display(Name = "Fabricante")]
        [Required(ErrorMessage = "El Fabricante es requerido")]
        public string Fabricante { get; set; }
        [Display(Name = "Fecha de compra")]
        [Required(ErrorMessage = "La fecha de compra es requerida")]
        public System.DateTime FechaCompra { get; set; }
        [Display(Name = "Costo del equipo")]
        [Required(ErrorMessage = "El costo del equipo es requerido")]
        public int CostoEquipo { get; set; }
        [Display(Name = "Garantia")]
        [Required(ErrorMessage = "La garantia es requerida")]
        public int Garantia { get; set; }
        [Display(Name = "Vencimiento de garantia")]
        [Required(ErrorMessage = "El Vencimiento de garantia es requerido")]
        public System.DateTime VenceGarantia { get; set; }
        [Display(Name = "Departamento")]
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> MotivoDeshabilitar { get; set; }
        public string ValorNuevo()
        {
            return "IdInventario:" + IdInventario.ToString() + " CodigoEmpresa:" + CodigoEmpresa + " Nombre:" + Nombre + " Modelo:" + Modelo + " Serie:" + Serie + " Fabricante:" + Fabricante + " FechaCompra" + FechaCompra.ToString() + " CostoEquipo:" + CostoEquipo + " Garantia:" + Garantia.ToString() + " VenceGarantia:" + VenceGarantia + " IdDepartamento:" + IdDepartamento;
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlInventario> ControlInventario { get; set; }
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoInventario> MantenimientoInventario { get; set; }
    }
}
