//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventario()
        {
            this.ControlInventario = new HashSet<ControlInventario>();
            this.MantenimientoInventario = new HashSet<MantenimientoInventario>();
        }
        [Display(Name = "Costo del vehículo")]
        public int IdInventario { get; set; }
        public string CodigoEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Modelo { get; set; }
        public string Serie { get; set; }
        public string Fabricante { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public int CostoEquipo { get; set; }
        public int Garantia { get; set; }
        public System.DateTime VenceGarantia { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> MotivoDeshabilitar { get; set; }
        public string ValorNuevo()
        {
            return "IdInventario:" + IdInventario.ToString() + " CodigoEmpresa:" + CodigoEmpresa + " Nombre:" + Nombre + " Modelo:" + Modelo + " Serie:" + Serie + " Fabricante:" + Fabricante + " FechaCompra" + FechaCompra.ToString() + " CostoEquipo:" + CostoEquipo + " Garantia:" + Garantia.ToString() + " VenceGarantia:" + VenceGarantia + " IdDepartamento:" + IdDepartamento;
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlInventario> ControlInventario { get; set; }
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoInventario> MantenimientoInventario { get; set; }
    }
}
