//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MantenimientoVehiculo
    {
        [Display(Name = "Id del mantenimiento del vehiculo")]
        public int IdMantenimientoVehiculo { get; set; }
        [Display(Name = "Flotilla")]
        public Nullable<int> IdFlotilla { get; set; }
        [Display(Name = "Tipo de mantenimiento")]
        [Required(ErrorMessage = "El tipo de mantenimiento es requerido")]
        public int TipoMantenimiento { get; set; }
        [Display(Name = "Kilometraje actual")]
        [Required(ErrorMessage = "El kilometraje es requerido")]
        public int KilometrajeActual { get; set; }
        [Display(Name = "Proximo kilometraje")]
        [Required(ErrorMessage = "El kilometraje es requerido")]
        public int ProximoKilometraje { get; set; }
        [Display(Name = "Costo del mantenimiento")]
        [Required(ErrorMessage = "El costo del mantenimiento es requerido")]
        public int CostoMantenimiento { get; set; }
        [Display(Name = "Fecha del mantenimiento")]
        [Required(ErrorMessage = "La fecha del mantenimiento es requerida")]
        public Nullable<System.DateTime> FechaMantenimiento { get; set; }
        [Display(Name = "Descripcion del servicio")]
        [Required(ErrorMessage = "La descripcion del servicio es requerida")]
        public string DescripcionServicio { get; set; }
        public string ValorNuevo()
        {
            return "IdMantenimientoVehiculo:" + IdMantenimientoVehiculo + " |IdFlotilla:" + IdFlotilla + " |TipoMantenimiento:" + TipoMantenimiento + "|CostoMantenimiento:" + CostoMantenimiento.ToString() + " |FechaMantenimiento:" + FechaMantenimiento + " |KilometrajeActual:" + KilometrajeActual + " |DescripcionServicio:" + DescripcionServicio + " |ProximoKilometraje:" + ProximoKilometraje;
        }
        public string ValorAntiguo(MantenimientoVehiculo Entidad)
        {
            return "IdMantenimientoVehiculo:" + Entidad.IdMantenimientoVehiculo + " |IdFlotilla:" + Entidad.IdFlotilla + " |TipoMantenimiento:" + Entidad.TipoMantenimiento + "|CostoMantenimiento:" + Entidad.CostoMantenimiento.ToString() + " |FechaMantenimiento:" + Entidad.FechaMantenimiento + " |KilometrajeActual:" + Entidad.KilometrajeActual + " |DescripcionServicio:" + Entidad.DescripcionServicio + " |ProximoKilometraje:" + Entidad.ProximoKilometraje;
        }

        public virtual Flotilla Flotilla { get; set; }
    }
}
