//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfiles_Permisos
    {
        public int Id_Permiso { get; set; }
        public Nullable<int> Id_Perfil { get; set; }
        public string Modulo { get; set; }
        public string Agregar { get; set; }
        public string Modificar { get; set; }
        public string Eliminar { get; set; }
    
        public virtual Perfiles_Acceso Perfiles_Acceso { get; set; }
    }
}
