//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.BitacoraIngresoSalida = new HashSet<BitacoraIngresoSalida>();
            this.BitacoraMovimiento = new HashSet<BitacoraMovimiento>();
        }
        [Display(Name = "Id del usuario")]
        public int IdUsuario { get; set; }
        [Display(Name = "Persona")]
        public Nullable<int> IdPersonal { get; set; }
        [Display(Name = "Perfil de acceso")]
        public Nullable<int> IdPerfiles { get; set; }
        [Display(Name = "Nombre de Usuario")]
        public string Usuario1 { get; set; }
        [Display(Name = "Contraseña")]
        [StringLength(100, ErrorMessage = "La contraseña debe de tener al menos {2} caracteres", MinimumLength = 8)]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[\d])(?=.*[A-Z])(?=.*[a-z])[\w\d]{8,}$", ErrorMessage = "La contraseña debe de tener un mínimo de 8 caracteres, con lo siguiente: " +
            "<ul>" +
            "<li>Al menos una <strong>mayúscula</strong></li>" +
            "<li>Al menos una <strong>minúscula</strong></li>" +
            "<li>Al menos un <strong>número</strong></li>" +
            "<li><strong>No</strong> debe tener caracteres especiales ni espacios</li>" +
            "</ul>")]
        public string Contraseña { get; set; }
        public string ValorNuevo()
        {
            return "IdUsuario:" + IdUsuario.ToString() + " |IdPersonal:" + IdPersonal.ToString() + " |IdPerfiles:" + IdPerfiles.ToString() + "|Usuario1:" + Usuario1 + " |Contraseña:" + Contraseña;
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraIngresoSalida> BitacoraIngresoSalida { get; set; }
        public virtual Perfiles_Acceso Perfiles_Acceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraMovimiento> BitacoraMovimiento { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
